MyApp/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using MyApp.DataBaseFolder;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using MyApp.Models;
using Microsoft.AspNetCore.Razor.Language.Intermediate;
using Microsoft.AspNetCore.Authorization;
using System.Text.RegularExpressions;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging.Signing;
using System.Linq;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Formats;
using System.Security.Cryptography;

namespace MyApp.Controllers
{
    public class ArticleController : Controller
    {
        private readonly IWebHostEnvironment _env;

        private DBContext context;
        public ArticleController(IWebHostEnvironment env, DBContext con) { _env = env; context = con; }

        [Authorize]
        
        [HttpGet]
        public IActionResult Index()
        {
            if (HttpContext.User.Identity.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Access");
            }

            return View();
        }

        //[HttpPost]
        //public IActionResult cringe(string title, string input)
        //{
        //    //Console.WriteLine(content);
            
        //    List<int> f = new List<int>();
        //    List<int> s = new List<int>();
        //    List<string> url = new List<string>();

        //    //string input = "<figure class=\"media\"><oembed url=\"https://www.youtube.com/watch?v=Z2XADS1HGOE\"></oembed></figure>";
        //    //string videoId = input.Split("https://www.youtube.com/watch?v=")[1].Split("\"")[0];

        //    string pattern1 = "<figure class=\"media\">";
        //    string pattern2 = "</oembed></figure>";
        //    string pattern3 = "https:\\/\\/www\\.youtube\\.com\\/watch\\?v=[a-zA-Z0-9_-]+";

        //    MatchCollection matches_f = Regex.Matches(input, pattern1), matches_s = Regex.Matches(input, pattern2),
        //        matches_url = Regex.Matches(input, pattern3);

        //    foreach (Match match in matches_f)
        //    {
        //        f.Add(match.Index);
        //    }

        //    foreach (Match match in matches_s)
        //    {
        //        s.Add(match.Index + 17);
        //    }

        //    foreach (Match match in matches_url)
        //    {
        //        url.Add(match.Value);
        //    }

        //    for (int i = 0; i < f.Count; i++) 
        //    {
        //        input = input.Remove(f[i], s[i] - f[i] + 1);

        //        input = input.Insert(f[i], $"<iframe width=\"560\" height=\"315\" src=\"{url[i].Replace("watch?v=", "embed/")}\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>");
        //    }

        //    //string output = $"<iframe width=\"560\" height=\"315\" src=\"{embedUrl}\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>";

        //    Article article = new Article();

        //    article.content = input;
        //    article.title = title;
        //    article.date = DateTime.Now.ToString("dd/MM/yyyy HH:mm");

        //    ClaimsPrincipal ClUser = HttpContext.User;

        //    List<Claim> cl = ClUser.Claims.ToList();

        //    foreach (Claim claim in cl) { Console.WriteLine(claim.Value); };

        //    var user = context.Users.Include(u => u.user_info).Where<User>(var => var.username == cl[0].Value && var.user_info.email == cl[2].Value).FirstOrDefault();



        //    return View("cringe", input);
        //}

        [HttpPost]
        public IActionResult CreateRequest(string categories, string title, IFormFile fileUpload, string input)
        {
            if (HttpContext.User.Identity.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Access");
            }

            var filepath = "";

            //C:\repos\MyApp\MyApp\wwwroot\Image


            if (fileUpload != null)
            {
                // Загружаем изображение в память
                using (var memoryStream = new MemoryStream())
                {
                    fileUpload.CopyTo(memoryStream);

                    memoryStream.Seek(0, SeekOrigin.Begin);

                    using (var image = Image.Load(memoryStream))
                    {
                        // Проверяем ширину и высоту изображения
                        if (image.Width != 1920 || image.Height != 1080)
                        {
                            filepath = "https://localhost:7012/Article_png/base.png";
                            goto h1;
                        }
                    }

                    string servermapath = Path.Combine(_env.WebRootPath, "Article_png", fileUpload.FileName);

                    using (var stream = new FileStream(servermapath, FileMode.Create))
                    {
                        fileUpload.CopyTo(stream);
                    }

                    filepath = "https://localhost:7012/Article_png/" + fileUpload.FileName;
                }
            }
            else
            {
                filepath = "https://localhost:7012/Article_png/base.png";
            }

            h1:

            //if (fileUpload != null)
            //{
                
                
                
                
                
                
            //    string servermapath = Path.Combine(_env.WebRootPath, "Article_png", fileUpload.FileName);

            //    using (var stream = new FileStream(servermapath, FileMode.Create))
            //    {
            //        fileUpload.CopyTo(stream);
            //    }

            //    filepath = "https://localhost:7012/" + "Article_png/" + fileUpload.FileName;
            //}
            //else 
            //{
            //    filepath = "https://localhost:7012/" + "Article_png/" + "base.png";
            //}

            string pattern_cat = "[A-Za-z0-9А-Яа-я]+";

            Category cat = new Category();

            cat.categoty_str = categories;

            //Console.WriteLine(content);

            List<int> f = new List<int>();
            List<int> s = new List<int>();
            List<string> url = new List<string>();

            //string input = "<figure class=\"media\"><oembed url=\"https://www.youtube.com/watch?v=Z2XADS1HGOE\"></oembed></figure>";
            //string videoId = input.Split("https://www.youtube.com/watch?v=")[1].Split("\"")[0];

            string pattern1 = "<figure class=\"media\">";
            string pattern2 = "</oembed></figure>";
            string pattern3 = "https:\\/\\/www\\.youtube\\.com\\/watch\\?v=[a-zA-Z0-9_-]+";

            MatchCollection matches_f = Regex.Matches(input, pattern1), matches_s = Regex.Matches(input, pattern2),
                matches_url = Regex.Matches(input, pattern3);

            foreach (Match match in matches_f)
            {
                f.Add(match.Index);
            }

            foreach (Match match in matches_s)
            {
                s.Add(match.Index + 17);
            }

            foreach (Match match in matches_url)
            {
                url.Add(match.Value);
            }

            for (int i = 0; i < f.Count; i++)
            {
                input = input.Remove(f[i], s[i] - f[i] + 1);

                input = input.Insert(f[i], $"<iframe width=\"560\" height=\"315\" src=\"{url[i].Replace("watch?v=", "embed/")}\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>");
            }

            //string output = $"<iframe width=\"560\" height=\"315\" src=\"{embedUrl}\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>";

            Article article = new Article();

            article.content = input;
            article.title = title;
            article.date = DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss");
            article.category = cat;
            article.path_to_corer = filepath;

            ClaimsPrincipal ClUser = HttpContext.User;

            List<Claim> cl = ClUser.Claims.ToList();

            var user = context.Users.Include(u => u.user_info).Include(a => a.channel_articles).Include(sub => sub.my_subscribes).Where<User>(var => var.username == cl[0].Value && var.user_info.email == cl[2].Value).FirstOrDefault();

            article.user = user;

            //context.Articles.Add(article);

            //context.SaveChanges();

            ArticleRequest req = new ArticleRequest();

            req.article = article;

            context.Requests.Add(req);

            context.SaveChanges();



            var ArticleReques = context.Requests.FirstOrDefault();

            return RedirectToAction("Account", "Access");
        }

        [HttpPost]

        public ActionResult UploadImage(List<IFormFile> files) 
        {
            if (HttpContext.User.Identity.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Access");
            }

            var filepath = "";

            foreach (IFormFile photo in Request.Form.Files) 
            {
                string servermapath = Path.Combine(_env.WebRootPath, "Image", photo.FileName);
                //C:\repos\MyApp\MyApp\wwwroot\Image

                using (var stream = new FileStream(servermapath, FileMode.Create)) 
                {
                    photo.CopyTo(stream);
                }

                filepath = "https://localhost:7012/" + "Image/" + photo.FileName;

                //https://localhost:7012/
            }


            return Json(new { url = filepath });
        }

        public IActionResult ViewArticle(int articleId)
        {

MyApp/Controllers/InformationController.cs
using Microsoft.AspNetCore.Mvc;
using MyApp.Models;
using System.Diagnostics;
using MyApp.DataBaseFolder;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Razor.Language.Intermediate;
using Microsoft.EntityFrameworkCore;
using Microsoft.CodeAnalysis.Options;
using Newtonsoft.Json.Linq;

namespace MyApp.Controllers
{
    public class InformationController : Controller
    {
        private readonly IWebHostEnvironment _env;

        private DBContext context;
        public InformationController(IWebHostEnvironment env, DBContext con) { _env = env; context = con; }
        public ActionResult Likes()
        {
            if (HttpContext.User.Identity.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Access");
            }

            ClaimsPrincipal ClUser = HttpContext.User;

            List<Claim> cl = ClUser.Claims.ToList();

            var user = context.Users.Include(u => u.user_info).Include(a => a.channel_articles).ThenInclude(u => u.comments).ThenInclude(u => u.creator).Include(a => a.channel_articles).ThenInclude(u => u.category).Include(sub => sub.my_subscribes).Where<User>(var => var.username == cl[0].Value && var.user_info.email == cl[2].Value).FirstOrDefault();

            List<Article> liked = new List<Article>();

            for(int counter = user.Liked_articles.Count - 1; counter > -1; counter--) 
            {
                int articleId = user.Liked_articles[counter];

                liked.Add(context.Articles.Include(com => com.comments).Include(cat => cat.category).Include(t => t.user).Include(a => a.user.user_info).Where(a => a.status == true && a.id == articleId).FirstOrDefault());
            }
            
            return View(liked);
        }

        public ActionResult Subs()
        {
            if (HttpContext.User.Identity.IsAuthenticated == false)
            {
                return RedirectToAction("Login", "Access");
            }

            ClaimsPrincipal ClUser = HttpContext.User;

            List<Claim> cl = ClUser.Claims.ToList();

            var user = context.Users.Include(u => u.user_info).Include(a => a.channel_articles).ThenInclude(u => u.comments).ThenInclude(u => u.creator).Include(a => a.channel_articles).ThenInclude(u => u.category).Include(sub => sub.my_subscribes).Where<User>(var => var.username == cl[0].Value && var.user_info.email == cl[2].Value).FirstOrDefault();

            return View(user.my_subscribes);
        }
    }
}

MyApp/Views/Shared/layouts/_Layout_admin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyApp.styles.css" asp-append-version="true" />

    <style>
        .left-nav {
            top: 70px;
            width: 190px;
            position: fixed;
            height: calc(100% - 70px);
            /* background-color: #ffffff; */
            padding: 10px;
            box-sizing: border-box;
        }

        .nav-link {
            /* display: flex; */ /* Элементы внутри будут расположены горизонтально */
            /*  align-items: center; */ /* Центрирование элементов по вертикали */
            /* text-decoration: none; */ /* Убираем подчеркивание текста */

            display: flex;
            align-items: center;
            padding-left: 10px; /* Добавлен отступ слева */
        }

            .nav-link i {
                /* margin-right: auto; */ /* Автоматический отступ справа, выравнивает текст после иконки */

                min-width: 30px; /* Минимальная ширина для иконок */
                margin-right: 10px; /* Отступ справа для иконок */
                text-align: center; /* Центрирование иконки внутри элемента */
            }

            .nav-link:hover {
                border: 2px solid #000; /* Черная обводка */
                background-color: rgba(0, 0, 0, 0.1); /* Затемнение фона */
            }

        .up-nav {
            padding: 11px;
            position: fixed; /* Фиксируем навигационную панель */
            top: 0; /* Располагаем её в верхней части экрана */
            width: 100%; /* Задаём ширину 100%, чтобы она растягивалась на всю ширину экрана */
            z-index: 1000; /* Устанавливаем z-index, чтобы навигационная панель была поверх других элементов */
            background-color: white;
            height: 70px;
        }

        .nav-link-special {
            font-size: 25px;
            font-weight: bold;
            color: #000; /* Черный цвет текста */
            text-decoration: none; /* Без подчеркивания */
            padding: 15px; /* Отступ вокруг текста */
        }

    </style>

    @* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"> *@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">
    <script src="https://kit.fontawesome.com/77e4e26825.js" crossorigin="anonymous"></script>

</head>

<body>

    <nav class="navbar navbar-expand-lg up-nav">
        <a class="nav-link-special text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-bookmark"></i> Статьи</a>

        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">


            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Logout"><i class="fas fa-sign-out-alt"></i> Выйти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Account"><i class="fas fa-user"></i> Аккаунт</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index"><i class="fa-solid fa-users"></i> Пользователи</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="left-nav">
        <nav>

            <a class="nav-link text-dark" style="font-size: 15px;" asp-area="" asp-controller="Theme" asp-action="Index"><i class="fa-solid fa-compass"></i> Темы</a>
            <a class="nav-link text-dark" style="font-size: 15px;" asp-area="" asp-controller="Information" asp-action="Subs"><i class="fa-solid fa-folder-open"></i> Подписки</a>
            <a class="nav-link text-dark" style="font-size: 15px;" asp-area="" asp-controller="Information" asp-action="Likes"><i class="fa-solid fa-heart"></i> Понравившиеся</a>
            @*  <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index"><i class="fas fa-plus-square"></i> CreateArticle</a> *@
            @* <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Logout"><i class="fas fa-sign-out-alt"></i> Logout</a> *@


        </nav>
    </div>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var initialWidth = window.innerWidth;

            function resizeHandler() {
                var screenWidth = window.innerWidth;
                var maxScreenWidth = initialWidth * 0.98;

                if (screenWidth <= maxScreenWidth) {
                    document.querySelector('.left-nav').style.display = 'none';
                } else {
                    document.querySelector('.left-nav').style.display = 'block';
                }
            }

            window.addEventListener('resize', resizeHandler);

            // Вызовите функцию обработчика события resize вручную
            resizeHandler();
        });
    </script>

</body>
</html>

MyApp/Views/Shared/layouts/_Layout_modder.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyApp.styles.css" asp-append-version="true" />

    <style>
        .left-nav {
            top: 70px;
            width: 190px;
            position: fixed;
            height: calc(100% - 70px);
            /* background-color: #ffffff; */
            padding: 10px;
            box-sizing: border-box;
        }

        .nav-link {
            /* display: flex; */ /* Элементы внутри будут расположены горизонтально */
            /*  align-items: center; */ /* Центрирование элементов по вертикали */
            /* text-decoration: none; */ /* Убираем подчеркивание текста */

            display: flex;
            align-items: center;
            padding-left: 10px; /* Добавлен отступ слева */
        }

            .nav-link i {
                /* margin-right: auto; */ /* Автоматический отступ справа, выравнивает текст после иконки */

                min-width: 30px; /* Минимальная ширина для иконок */
                margin-right: 10px; /* Отступ справа для иконок */
                text-align: center; /* Центрирование иконки внутри элемента */
            }

            .nav-link:hover {
                border: 2px solid #000; /* Черная обводка */
                background-color: rgba(0, 0, 0, 0.1); /* Затемнение фона */
            }

        .up-nav {
            padding: 11px;
            position: fixed; /* Фиксируем навигационную панель */
            top: 0; /* Располагаем её в верхней части экрана */
            width: 100%; /* Задаём ширину 100%, чтобы она растягивалась на всю ширину экрана */
            z-index: 1000; /* Устанавливаем z-index, чтобы навигационная панель была поверх других элементов */
            background-color: white;
            height: 70px;
        }

        .nav-link-special {
            font-size: 25px;
            font-weight: bold;
            color: #000; /* Черный цвет текста */
            text-decoration: none; /* Без подчеркивания */
            padding: 15px; /* Отступ вокруг текста */
        }

        /* 1630px */

        /* @@media (max-width: 80%){
                    .left-nav{
                        display: none;
                    }
                } */

    </style>

    @* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"> *@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">
    <script src="https://kit.fontawesome.com/77e4e26825.js" crossorigin="anonymous"></script>

</head>

<body>

    <nav class="navbar navbar-expand-lg up-nav">
        <a class="nav-link-special text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-bookmark"></i> Статьи</a>

        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">


            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Logout"><i class="fas fa-sign-out-alt"></i> Выйти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Account"><i class="fas fa-user"></i> Аккаунт</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="left-nav">
        <nav>

            <a class="nav-link text-dark" style="font-size: 15px;" asp-area="" asp-controller="Theme" asp-action="Index"><i class="fa-solid fa-compass"></i> Темы</a>
            <a class="nav-link text-dark" style="font-size: 15px;" asp-area="" asp-controller="Information" asp-action="Subs"><i class="fa-solid fa-folder-open"></i> Подписки</a>
            <a class="nav-link text-dark" style="font-size: 15px;" asp-area="" asp-controller="Information" asp-action="Likes"><i class="fa-solid fa-heart"></i> Понравившиеся</a>
           @*  <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index"><i class="fas fa-plus-square"></i> CreateArticle</a> *@
            @* <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Logout"><i class="fas fa-sign-out-alt"></i> Logout</a> *@


        </nav>
    </div>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var initialWidth = window.innerWidth;

            function resizeHandler() {
                var screenWidth = window.innerWidth;
                var maxScreenWidth = initialWidth * 0.98;

                if (screenWidth <= maxScreenWidth) {
                    document.querySelector('.left-nav').style.display = 'none';
                } else {
                    document.querySelector('.left-nav').style.display = 'block';
                }
            }

            window.addEventListener('resize', resizeHandler);

            // Вызовите функцию обработчика события resize вручную
            resizeHandler();
        });
    </script>

</body>
</html>

MyApp/Views/Shared/layouts/_Layout_user.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyApp.styles.css" asp-append-version="true" />

    <style>
        .left-nav {
            top: 70px;
            width: 190px;
            position: fixed;
            height: calc(100% - 70px);
            /* background-color: #ffffff; */
            padding: 10px;
            box-sizing: border-box;
        }

        .nav-link {
            /* display: flex; */ /* Элементы внутри будут расположены горизонтально */
            /*  align-items: center; */ /* Центрирование элементов по вертикали */
            /* text-decoration: none; */ /* Убираем подчеркивание текста */

            display: flex;
            align-items: center;
            padding-left: 10px; /* Добавлен отступ слева */
        }

            .nav-link i {
                /* margin-right: auto; */ /* Автоматический отступ справа, выравнивает текст после иконки */

                min-width: 30px; /* Минимальная ширина для иконок */
                margin-right: 10px; /* Отступ справа для иконок */
                text-align: center; /* Центрирование иконки внутри элемента */
            }

            .nav-link:hover {
                border: 2px solid #000; /* Черная обводка */
                background-color: rgba(0, 0, 0, 0.1); /* Затемнение фона */
            }

        .up-nav {
            padding: 11px;
            position: fixed; /* Фиксируем навигационную панель */
            top: 0; /* Располагаем её в верхней части экрана */
            width: 100%; /* Задаём ширину 100%, чтобы она растягивалась на всю ширину экрана */
            z-index: 1000; /* Устанавливаем z-index, чтобы навигационная панель была поверх других элементов */
            background-color: white;
            height: 70px;
        }

        .nav-link-special {
            font-size: 25px;
            font-weight: bold;
            color: #000; /* Черный цвет текста */
            text-decoration: none; /* Без подчеркивания */
            padding: 15px; /* Отступ вокруг текста */
        }

        /* 1630px */

        /* @@media (max-width: 80%){
            .left-nav{
                display: none;
            }
        } */

    </style>

    @* <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"> *@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">
    <script src="https://kit.fontawesome.com/77e4e26825.js" crossorigin="anonymous"></script>

</head>

<body>

    <nav class="navbar navbar-expand-lg up-nav">
        <a class="nav-link-special text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-bookmark"></i> Статьи</a>

        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">


            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Logout"><i class="fas fa-sign-out-alt"></i> Выйти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Account"><i class="fas fa-user"></i> Аккаунт</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="left-nav">
        <nav>

            <a class="nav-link text-dark" style="font-size: 15px;" asp-area="" asp-controller="Theme" asp-action="Index"><i class="fa-solid fa-compass"></i> Темы</a>
            <a class="nav-link text-dark" style="font-size: 15px;" asp-area="" asp-controller="Information" asp-action="Subs"><i class="fa-solid fa-folder-open"></i> Подписки</a>
            <a class="nav-link text-dark" style="font-size: 15px;" asp-area="" asp-controller="Information" asp-action="Likes"><i class="fa-solid fa-heart"></i> Понравившиеся</a>
            @* <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index"><i class="fas fa-plus-square"></i> CreateArticle</a> *@
            @* <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Logout"><i class="fas fa-sign-out-alt"></i> Logout</a> *@

        </nav>
    </div>

    

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var initialWidth = window.innerWidth;

            function resizeHandler() {
                var screenWidth = window.innerWidth;
                var maxScreenWidth = initialWidth*0.98;

                if (screenWidth <= maxScreenWidth) {
                    document.querySelector('.left-nav').style.display = 'none';
                } else {
                    document.querySelector('.left-nav').style.display = 'block';
                }
            }

            window.addEventListener('resize', resizeHandler);

            // Вызовите функцию обработчика события resize вручную
            resizeHandler();
        });
    </script>

</body>
</html>